### ISSUE TITLE
What licenses are required on the Windows side to run Iceberg? Does not work with PAS for OE PROD Bundle.

### ISSUE THREAD

**Issue by mirgpt** [progress/iceberg#37]
On Windows, when Progress is installed using PAS for OE PROD Bundle, oemanager.bat does not work.

proenv>oemanager.bat status
C:\OpenEdge\WRK\training\utils\oemanager.xml:621: Execute failed: java.io.IOException: Cannot run program "C:\Progress\OpenEdge\bin\_progres" (in directory "C:\OpenEdge\WRK\training\utils"): CreateProcess error=2, The system cannot find the file specified

Using OE 12.8.1 on Windows 2016.

We install PASOE application server via the OE PROD Bundle, but it looks like iceberg has a dependency on _progress binary, and that does not ship with this license SKU.

Is this expected and what is the minimum licensing on Windows required to run Iceberg?

**Comment by DustinGrau-PSC** [comment]
As this is a question regarding the shipped product, it would be best that your inquiry go through standard tech support channels to ensure it can be addressed correctly.
