### ISSUE TITLE
Ability to trim specific session/agent?

### ISSUE THREAD

**Issue by c3rberus** [progress/iceberg#4]
These are very useful tools to monitor PAS, fills the gap since we can no longer use asbman to pull status, stacks and kill procs.

It would be useful (as a feature enhancement) to add the ability to terminate specific sessions/agents instead of all and/or idle, that way we can use this tool to terminate stuck sessions/threads.

**Comment by c3rberus** [comment]
I'll check out OE Management Console, although it would be nice to have something readily available in the cli to replace the legacy methods (asbman -agentkill #pid) when needing to terminate a specific running agent (in this case of pas, thread/session).

**Comment by DustinGrau-PSC** [comment]
That's an understandable suggestion but unfortunately not something I can implement at a product level. Your best option is to submit an idea for CLI tooling for PAS via the OpenEdge Ideas portal. This will reach the right people and allow the community to vote up the idea for consideration. Be sure to include all of the actions that you feel are missing and should be made available.
https://openedge.ideas.aha.io/

**Comment by DustinGrau-PSC** [comment]
The latest merge introduces the ability to pass a PID to the "stop" task, or a session ID to the "trimhttp" task. This should satisfy the requested changes in respect to how the task should be used. The usage instructions for the tasks has been updated and adjusted to account for the new changes and to help with choosing the correct task for dealing with "stuck" sessions.

**Comment by c3rberus** [comment]
This is great news, thank you for adding this feature.
