### ISSUE TITLE
Activate metrics shutdown available agent

### ISSUE THREAD

**Issue by PeterWokke** [progress/iceberg#5]
I have implemented the monitor and application on OpenEdge 12.2.3. 
When activate the metrics on the application I encountered the following behavior.
The metrics was set on the available agent. The agent shutdown and a new agent was started.
The new agent was not available during the activate procedure. Basically the monitor on this application was only pushing his short live time info to the monitor.

Solution is an upgrade to 12.2.7 or higher.

**Comment by DustinGrau-PSC** [comment]
Thank you for capturing this particular issue and resolution, Peter. While I cannot wager the cause of your exact issue, the OpenEdge LTS release 12.2.4 has become a minimum version for many of our tools, though I realize the documentation here makes reference to 12.2.3--I'll change that to be more specific. In general it is highly recommended to keep up to date with service packs as your maintenance windows allow.

**Comment by DustinGrau-PSC** [comment]
I have since updated our README files in the repo to reflect more accurate minimum versions for where tools can run reliably.
